name: CI/CD
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [run-deploy]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          
      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Released Tag
        uses: jaywcjlove/create-tag-action@main
        with:
          version: ${{ steps.create_tag.outputs.version }}
          release: true
          body: |
            <a target="_blank" href="https://apps.apple.com/app/videoer/6742680573" title="Videoer for macOS">
              <img alt="Videoer AppStore" src="https://jaywcjlove.github.io/sb/download/macos.svg" height="51">
            </a>

      - name: Create idoc config.
        run: |
          cat > idoc.yml << EOF
          site: "PasteQuick {{version:${{ steps.create_tag.outputs.version }}}}"
          description: A privacy-focused and simple clipboard management tool that enables efficient handling of various temporary data types, including text, links, images, and code.
          keywords: PasteQuick, clipboard manager, privacy tool, data management, text management, image management, link manager, code snippet manager, macOS app
          favicon: assets/logo.png
          logo: ./assets/logo.png
          openSource: https://github.com/jaywcjlove/paste-quick
          homepage: https://wangchujiang.com/paste-quick/
          tocs: false
          element: 
            wrapper: style=max-width:720px;
          meta:
            - <meta name="author" content="Kenny Wong">
            - <meta property="og:site_name" content="<%= site %>">
            - <meta property="og:url" content="<%=homepage%><%=RESOLVE_PATH%>">
            - <meta property="og:image" content="<%=homepage%>assets/logo.png">
            - <meta property="og:type" content="application">
            - <meta property="og:title" content="<%= site %>">
            - <meta property="og:description" content="<%= description%>">
            - <meta property="twitter:image:src" content="<%=homepage%>assets/social-preview.png">
            - <meta property="twitter:site" content="@jaywcjlove">
            - <meta property="twitter:creator" content="jaywcjlove">
            - <meta property="twitter:card" content="summary_large_image">
            - <meta property="twitter:title" content="<%= site %> - <%= description%>">
            - <meta property="twitter:description" content="<%= description%>">
            - <meta name="apple-itunes-app" content="app-id=6670696072">
          menus:
            Home: index.html
            Apps: 
              url: https://wangchujiang.com/#/app
              target: __blank
            Feeds: 
              url: feeds/index.html
              target: __blank
          sideEffectFiles:
            - README.md
            - README.zh.md
            - CHANGELOG.md
            - CHANGELOG.zh.md
            - terms-of-service.md
            - feedback.md
            - feedback.zh.md
            - terms-of-service.zh.md
            - privacy-policy.md
            - privacy-policy.zh.md
          footer: |
            <a href="./terms-of-service.html" target="_blank">Terms of Service</a> • 
            <a href="./privacy-policy.html" target="_blank">Privacy Policy</a> • 
            <a href="https://wangchujiang.com/#/projects" target="_blank">Projects</a> • 
            <a href="https://wangchujiang.com/#/sponsor" target="_blank">Sponsor</a> • 
            <a href="https://wangchujiang.com/#/app" target="_blank">More Apps</a><br /><br />
            Generated by <a href="https://github.com/jaywcjlove/idoc" target="_blank">idoc</a> v{{idocVersion}}      
          EOF

      - run: npm install idoc@1 -g
      - run: idoc
      - run: cp -rp assets/social-preview.png dist/assets/
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist